name: GitHub-Profile-3D-Contrib

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Generate snake animation"]  # Name of your snake workflow
    types:
      - completed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Checkout output branch
        uses: actions/checkout@v2
        with:
            ref: output
            path: profile-3d-contrib
                # Update just the profile-3d directory
      - name: Update profile-3d directory
        run: |
            # Create profile-3d directory if it doesn't exist
            mkdir -p profile-3d-contrib/profile-3d
            
            # Copy newly generated files to the existing profile-3d directory
            cp -r profile-3d-contrib/* profile-3d-contrib/profile-3d/
            
            # Verify the files are there
            echo "Contents of profile-3d directory:"
            ls -la existing-output/profile-3d/
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
            target_branch: output
            build_dir: profile-3d-contrib
            commit_message: "Update 3D Contrib animation"
            keep_history: true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
